# Generated by Django 6.0.1 on 2026-01-21 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=datetime.date(2026, 1, 21)),
            preserve_default=False,
        ),
    ]
